import Foundation

/// Provider-defined custom content generated by a model.
public struct LanguageModelV3CustomContent: Sendable, Equatable, Codable {
    public let type: String = "custom"
    public let kind: String
    public let providerMetadata: SharedV3ProviderMetadata?

    public init(kind: String, providerMetadata: SharedV3ProviderMetadata? = nil) {
        self.kind = kind
        self.providerMetadata = providerMetadata
    }

    private enum CodingKeys: String, CodingKey {
        case type, kind, providerMetadata
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        kind = try container.decode(String.self, forKey: .kind)
        providerMetadata = try container.decodeIfPresent(SharedV3ProviderMetadata.self, forKey: .providerMetadata)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(kind, forKey: .kind)
        try container.encodeIfPresent(providerMetadata, forKey: .providerMetadata)
    }
}
