import Foundation

/**
 Error thrown when no object could be generated.

 Port of `@ai-sdk/ai/src/error/no-object-generated-error.ts`.

 This can have several causes:
 - The model failed to generate a response.
 - The model generated a response that could not be parsed.
 - The model generated a response that could not be validated against the schema.

 The error contains the following properties:
 - `text`: The text that was generated by the model. This can be the raw text
   or the tool call text, depending on the model.
 */
public struct NoObjectGeneratedError: AISDKError, Sendable {
    public static let errorDomain = "ai.error.NoObjectGeneratedError"

    public let name = "AI_NoObjectGeneratedError"
    public let message: String
    public let cause: (any Error)?

    /// The text that was generated by the model.
    /// This can be the raw text or the tool call text, depending on the model.
    public let text: String?

    /// The response metadata.
    public let response: LanguageModelResponseMetadata?

    /// The usage of the model.
    public let usage: LanguageModelUsage?

    /// Reason why the model finished generating a response.
    public let finishReason: FinishReason?

    public init(
        message: String? = nil,
        cause: (any Error)? = nil,
        text: String? = nil,
        response: LanguageModelResponseMetadata,
        usage: LanguageModelUsage,
        finishReason: FinishReason
    ) {
        self.message = message ?? "No object generated."
        self.cause = cause
        self.text = text
        self.response = response
        self.usage = usage
        self.finishReason = finishReason
    }

    public static func isInstance(_ error: any Error) -> Bool {
        SwiftAISDK.hasMarker(error, marker: errorDomain)
    }
}
