import Foundation
import AISDKProvider
import AISDKProviderUtils

/**
 A message that was generated during the generation process.
 It can be either an assistant message or a tool message.

 Port of `@ai-sdk/ai/src/generate-text/response-message.ts`.
 */
public enum ResponseMessage: Sendable {
    /// An assistant message generated by the model.
    case assistant(AssistantModelMessage)

    /// A tool message with tool results.
    case tool(ToolModelMessage)
}
