name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Tests
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Cache SPM dependencies
      uses: actions/cache@v4
      with:
        path: |
          .build
          ~/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - name: Select Xcode 16.4
      run: sudo xcode-select -s /Applications/Xcode_16.4.app

    - name: Swift version
      run: swift --version

    - name: Build
      run: swift build -v

    - name: Run tests with coverage
      run: swift test -v --enable-code-coverage

    - name: Generate coverage report
      run: |
        xcrun llvm-cov export -format="lcov" \
          .build/debug/SwiftAISDKPackageTests.xctest/Contents/MacOS/SwiftAISDKPackageTests \
          -instr-profile .build/debug/codecov/default.profdata > coverage.lcov

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.lcov
        fail_ci_if_error: false
