name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14, macos-15]
        swift: ["6.0", "6.1"]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_16.1.app
      if: matrix.os == 'macos-15'

    - name: Swift version
      run: swift --version

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v
