name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Tests
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Select Xcode 16.1
      run: sudo xcode-select -s /Applications/Xcode_16.1.app

    - name: Swift version
      run: swift --version

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v
